# .github/workflows/main.yml

name: Pipeline de CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar ambiente Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes de unidade
      run: python -m unittest discover tests
      
    - name: Executar análise de segurança com Bandit
      run: |
        pip install bandit
        bandit -r src/

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Construir e Enviar imagem Docker
      run: |
        docker build -t cocati/estufa-inteligente:latest .
        docker push cocati/estufa-inteligente:latest