# .github/workflows/main.yml

name: Pipeline de CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar ambiente Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes de unidade
      run: python -m unittest discover tests
      
    - name: Executar análise de segurança com Bandit
      run: |
        pip install bandit
        bandit -r src/

    - name: Construir imagem Docker
      # Esta etapa constrói a imagem do container, usando o Dockerfile
      run: docker build -t estufa-inteligente .

    # --- Próximos passos do pipeline ---
    # Etapa de Deploy Contínuo:
    # AQUI você adicionaria a lógica para implantar
    # sua aplicação em um servidor de produção.